### PR TITLE
v0.3.05

### PR DESCRIPTION
**Pull request by Ghawken**
Add Digest Authenication Option for devices (devices will need to be open and re-saved)
Change to JSON - enabling support for Json Lists

### CODE REVIEW

**Review by DaveL17 — COMMENTED** [review]
These changes are great.  I will be making a few edits before merging them.  Should be today sometime.

**Review by DaveL17 — CHANGES_REQUESTED** [review]
Thank you very much!  I will send you a private message through the Indigo forum with a few suggestions.

**Comment by Ghawken** [comment]
Hi

**Thought easier to reply here:**

If using multiple list option:  This one:

`[{"serialNumber":"121630050316","lastReportDate":1480302511,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046735","lastReportDate":1480302509,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121632058899","lastReportDate":1480302472,"devType":1,"lastReportWatts":227,"maxReportWatts":270},{"serialNumber":"121630046772","lastReportDate":1480302474,"devType":1,"lastReportWatts":224,"maxReportWatts":270},{"serialNumber":"121630046255","lastReportDate":1480302478,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046238","lastReportDate":1480302485,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046227","lastReportDate":1480302481,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630050703","lastReportDate":1480302485,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630050397","lastReportDate":1480302492,"devType":1,"lastReportWatts":228,"maxReportWatts":270},{"serialNumber":"121630050272","lastReportDate":1480302489,"devType":1,"lastReportWatts":223,"maxReportWatts":270},{"serialNumber":"121630046782","lastReportDate":1480302499,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046206","lastReportDate":1480302507,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046661","lastReportDate":1480302514,"devType":1,"lastReportWatts":264,"maxReportWatts":270},{"serialNumber":"121630050417","lastReportDate":1480302514,"devType":1,"lastReportWatts":269,"maxReportWatts":271},{"serialNumber":"121630044744","lastReportDate":1480302446,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121630044459","lastReportDate":1480302453,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121630046708","lastReportDate":1480302458,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121630050211","lastReportDate":1480302463,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630050381","lastReportDate":1480302469,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046741","lastReportDate":1480302474,"devType":1,"lastReportWatts":225,"maxReportWatts":270},{"serialNumber":"121630046107","lastReportDate":1480302470,"devType":1,"lastReportWatts":265,"maxReportWatts":270},{"serialNumber":"121630050251","lastReportDate":1480302468,"devType":1,"lastReportWatts":270,"maxReportWatts":270},{"serialNumber":"121630046501","lastReportDate":1480302467,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121630046862","lastReportDate":1480302466,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046258","lastReportDate":1480302461,"devType":1,"lastReportWatts":265,"maxReportWatts":271},{"serialNumber":"121630046479","lastReportDate":1480302461,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630050383","lastReportDate":1480302459,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046432","lastReportDate":1480302457,"devType":1,"lastReportWatts":226,"maxReportWatts":270},{"serialNumber":"121630046250","lastReportDate":1480302455,"devType":1,"lastReportWatts":263,"maxReportWatts":271},{"serialNumber":"121630046308","lastReportDate":1480302452,"devType":1,"lastReportWatts":265,"maxReportWatts":271},{"serialNumber":"121630044455","lastReportDate":1480302450,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046485","lastReportDate":1480302448,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046769","lastReportDate":1480302447,"devType":1,"lastReportWatts":226,"maxReportWatts":270},{"serialNumber":"121630044415","lastReportDate":1480302515,"devType":1,"lastReportWatts":223,"maxReportWatts":270},{"serialNumber":"121630046779","lastReportDate":1480302518,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121632058618","lastReportDate":1480302518,"devType":1,"lastReportWatts":227,"maxReportWatts":270},{"serialNumber":"121630046205","lastReportDate":1480302476,"devType":1,"lastReportWatts":268,"maxReportWatts":270},{"serialNumber":"121630050349","lastReportDate":1480302482,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630050337","lastReportDate":1480302487,"devType":1,"lastReportWatts":223,"maxReportWatts":270},{"serialNumber":"121630046247","lastReportDate":1480302499,"devType":1,"lastReportWatts":261,"maxReportWatts":270},{"serialNumber":"121630046662","lastReportDate":1480302495,"devType":1,"lastReportWatts":261,"maxReportWatts":271},{"serialNumber":"121630046823","lastReportDate":1480302502,"devType":1,"lastReportWatts":221,"maxReportWatts":270},{"serialNumber":"121630046658","lastReportDate":1480302510,"devType":1,"lastReportWatts":259,"maxReportWatts":270},{"serialNumber":"121630050271","lastReportDate":1480302505,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046257","lastReportDate":1480302503,"devType":1,"lastReportWatts":262,"maxReportWatts":270},{"serialNumber":"121630050298","lastReportDate":1480302494,"devType":1,"lastReportWatts":225,"maxReportWatts":270},{"serialNumber":"121630050387","lastReportDate":1480302476,"devType":1,"lastReportWatts":269,"maxReportWatts":270},{"serialNumber":"121630046801","lastReportDate":1480302483,"devType":1,"lastReportWatts":222,"maxReportWatts":270},{"serialNumber":"121630046642","lastReportDate":1480302489,"devType":1,"lastReportWatts":222,"maxReportWatts":270},{"serialNumber":"121630046797","lastReportDate":1480302497,"devType":1,"lastReportWatts":269,"maxReportWatts":270}]`

simplejson.loads()

Gives us a list.
`[{u'devType': 1, u'serialNumber': u'121630050316', u'lastReportDate': 1480302511, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046735', u'lastReportDate': 1480302509, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121632058899', u'lastReportDate': 1480302472, u'maxReportWatts': 270, u'lastReportWatts': 227}, {u'devType': 1, u'serialNumber': u'121630046772', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 224}, {u'devType': 1, u'serialNumber': u'121630046255', u'lastReportDate': 1480302478, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046238', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046227', u'lastReportDate': 1480302481, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050703', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050397', u'lastReportDate': 1480302492, u'maxReportWatts': 270, u'lastReportWatts': 228}, {u'devType': 1, u'serialNumber': u'121630050272', u'lastReportDate': 1480302489, u'maxReportWatts': 270, u'lastReportWatts': 223}, {u'devType': 1, u'serialNumber': u'121630046782', u'lastReportDate': 1480302499, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046206', u'lastReportDate': 1480302507, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046661', u'lastReportDate': 1480302514, u'maxReportWatts': 270, u'lastReportWatts': 264}, {u'devType': 1, u'serialNumber': u'121630050417', u'lastReportDate': 1480302514, u'maxReportWatts': 271, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630044744', u'lastReportDate': 1480302446, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630044459', u'lastReportDate': 1480302453, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630046708', u'lastReportDate': 1480302458, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630050211', u'lastReportDate': 1480302463, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050381', u'lastReportDate': 1480302469, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046741', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 225}, {u'devType': 1, u'serialNumber': u'121630046107', u'lastReportDate': 1480302470, u'maxReportWatts': 270, u'lastReportWatts': 265}, {u'devType': 1, u'serialNumber': u'121630050251', u'lastReportDate': 1480302468, u'maxReportWatts': 270, u'lastReportWatts': 270}, {u'devType': 1, u'serialNumber': u'121630046501', u'lastReportDate': 1480302467, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630046862', u'lastReportDate': 1480302466, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046258', u'lastReportDate': 1480302461, u'maxReportWatts': 271, u'lastReportWatts': 265}, {u'devType': 1, u'serialNumber': u'121630046479', u'lastReportDate': 1480302461, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050383', u'lastReportDate': 1480302459, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046432', u'lastReportDate': 1480302457, u'maxReportWatts': 270, u'lastReportWatts': 226}, {u'devType': 1, u'serialNumber': u'121630046250', u'lastReportDate': 1480302455, u'maxReportWatts': 271, u'lastReportWatts': 263}, {u'devType': 1, u'serialNumber': u'121630046308', u'lastReportDate': 1480302452, u'maxReportWatts': 271, u'lastReportWatts': 265}, {u'devType': 1, u'serialNumber': u'121630044455', u'lastReportDate': 1480302450, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046485', u'lastReportDate': 1480302448, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046769', u'lastReportDate': 1480302447, u'maxReportWatts': 270, u'lastReportWatts': 226}, {u'devType': 1, u'serialNumber': u'121630044415', u'lastReportDate': 1480302515, u'maxReportWatts': 270, u'lastReportWatts': 223}, {u'devType': 1, u'serialNumber': u'121630046779', u'lastReportDate': 1480302518, u'maxReportWatts': 270, u'lastReportWatts': 268}]
[{u'devType': 1, u'serialNumber': u'121630050316', u'lastReportDate': 1480302511, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046735', u'lastReportDate': 1480302509, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121632058899', u'lastReportDate': 1480302472, u'maxReportWatts': 270, u'lastReportWatts': 227}, {u'devType': 1, u'serialNumber': u'121630046772', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 224}, {u'devType': 1, u'serialNumber': u'121630046255', u'lastReportDate': 1480302478, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046238', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046227', u'lastReportDate': 1480302481, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050703', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050397', u'lastReportDate': 1480302492, u'maxReportWatts': 270, u'lastReportWatts': 228}, {u'devType': 1, u'serialNumber': u'121630050272', u'lastReportDate': 1480302489, u'maxReportWatts': 270, u'lastReportWatts': 223}, {u'devType': 1, u'serialNumber': u'121630046782', u'lastReportDate': 1480302499, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046206', u'lastReportDate': 1480302507, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046661', u'lastReportDate': 1480302514, u'maxReportWatts': 270, u'lastReportWatts': 264}, {u'devType': 1, u'serialNumber': u'121630050417', u'lastReportDate': 1480302514, u'maxReportWatts': 271, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630044744', u'lastReportDate': 1480302446, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630044459', u'lastReportDate': 1480302453, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630046708', u'lastReportDate': 1480302458, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630050211', u'lastReportDate': 1480302463, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050381', u'lastReportDate': 1480302469, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046741', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 225}, {u'devType': 1, u'serialNumber': u'121630046107', u'lastReportDate': 1480302470, u'maxReportWatts': 270, u'lastReportWatts': 265}, {u'devType': 1, u'serialNumber': u'121630050251', u'lastReportDate': 1480302468, u'maxReportWatts': 270, u'lastReportWatts': 270}, {u'devType': 1, u'serialNumber': u'121630046501', u'lastReportDate': 1480302467, u'maxReportWatts': 270, u'lastReportWatts': 268}, {u'devType': 1, u'serialNumber': u'121630046862', u'lastReportDate': 1480302466, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046258', u'lastReportDate': 1480302461, u'maxReportWatts': 271, u'lastReportWatts': 265}, {u'devType': 1, u'serialNumber': u'121630046479', u'lastReportDate': 1480302461, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630050383', u'lastReportDate': 1480302459, u'maxReportWatts': 270, u'lastReportWatts': 269}, {u'devType': 1, u'serialNumber': u'121630046432', u'lastReportDate':`

No way to to open first one.  (probably some buffer issues - not copying all the output)

We are going to have to iterate through all - which is what 
`parsed_simplejson = dict(("No_"+str(i),v) for  (i,v) in enumerate(parsed_simplejson))`

Does well - with this output.

`{'No_4': {u'devType': 1, u'serialNumber': u'121630046255', u'lastReportDate': 1480302478, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_5': {u'devType': 1, u'serialNumber': u'121630046238', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_6': {u'devType': 1, u'serialNumber': u'121630046227', u'lastReportDate': 1480302481, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_7': {u'devType': 1, u'serialNumber': u'121630050703', u'lastReportDate': 1480302485, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_0': {u'devType': 1, u'serialNumber': u'121630050316', u'lastReportDate': 1480302511, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_1': {u'devType': 1, u'serialNumber': u'121630046735', u'lastReportDate': 1480302509, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_2': {u'devType': 1, u'serialNumber': u'121632058899', u'lastReportDate': 1480302472, u'maxReportWatts': 270, u'lastReportWatts': 227}, 'No_3': {u'devType': 1, u'serialNumber': u'121630046772', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 224}, 'No_8': {u'devType': 1, u'serialNumber': u'121630050397', u'lastReportDate': 1480302492, u'maxReportWatts': 270, u'lastReportWatts': 228}, 'No_9': {u'devType': 1, u'serialNumber': u'121630050272', u'lastReportDate': 1480302489, u'maxReportWatts': 270, u'lastReportWatts': 223}, 'No_32': {u'devType': 1, u'serialNumber': u'121630046769', u'lastReportDate': 1480302447, u'maxReportWatts': 270, u'lastReportWatts': 226}, 'No_23': {u'devType': 1, u'serialNumber': u'121630046862', u'lastReportDate': 1480302466, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_22': {u'devType': 1, u'serialNumber': u'121630046501', u'lastReportDate': 1480302467, u'maxReportWatts': 270, u'lastReportWatts': 268}, 'No_21': {u'devType': 1, u'serialNumber': u'121630050251', u'lastReportDate': 1480302468, u'maxReportWatts': 270, u'lastReportWatts': 270}, 'No_20': {u'devType': 1, u'serialNumber': u'121630046107', u'lastReportDate': 1480302470, u'maxReportWatts': 270, u'lastReportWatts': 265}, 'No_27': {u'devType': 1, u'serialNumber': u'121630046432', u'lastReportDate': 1480302457, u'maxReportWatts': 270, u'lastReportWatts': 226}, 'No_26': {u'devType': 1, u'serialNumber': u'121630050383', u'lastReportDate': 1480302459, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_25': {u'devType': 1, u'serialNumber': u'121630046479', u'lastReportDate': 1480302461, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_24': {u'devType': 1, u'serialNumber': u'121630046258', u'lastReportDate': 1480302461, u'maxReportWatts': 271, u'lastReportWatts': 265}, 'No_29': {u'devType': 1, u'serialNumber': u'121630046308', u'lastReportDate': 1480302452, u'maxReportWatts': 271, u'lastReportWatts': 265}, 'No_28': {u'devType': 1, u'serialNumber': u'121630046250', u'lastReportDate': 1480302455, u'maxReportWatts': 271, u'lastReportWatts': 263}, 'No_16': {u'devType': 1, u'serialNumber': u'121630046708', u'lastReportDate': 1480302458, u'maxReportWatts': 270, u'lastReportWatts': 268}, 'No_17': {u'devType': 1, u'serialNumber': u'121630050211', u'lastReportDate': 1480302463, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_14': {u'devType': 1, u'serialNumber': u'121630044744', u'lastReportDate': 1480302446, u'maxReportWatts': 270, u'lastReportWatts': 268}, 'No_15': {u'devType': 1, u'serialNumber': u'121630044459', u'lastReportDate': 1480302453, u'maxReportWatts': 270, u'lastReportWatts': 268}, 'No_12': {u'devType': 1, u'serialNumber': u'121630046661', u'lastReportDate': 1480302514, u'maxReportWatts': 270, u'lastReportWatts': 264}, 'No_13': {u'devType': 1, u'serialNumber': u'121630050417', u'lastReportDate': 1480302514, u'maxReportWatts': 271, u'lastReportWatts': 269}, 'No_10': {u'devType': 1, u'serialNumber': u'121630046782', u'lastReportDate': 1480302499, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_11': {u'devType': 1, u'serialNumber': u'121630046206', u'lastReportDate': 1480302507, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_34': {u'devType': 1, u'serialNumber': u'121630046779', u'lastReportDate': 1480302518, u'maxReportWatts': 270, u'lastReportWatts': 268}, 'No_33': {u'devType': 1, u'serialNumber': u'121630044415', u'lastReportDate': 1480302515, u'maxReportWatts': 270, u'lastReportWatts': 223}, 'No_30': {u'devType': 1, u'serialNumber': u'121630044455', u'lastReportDate': 1480302450, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_31': {u'devType': 1, u'serialNumber': u'121630046485', u'lastReportDate': 1480302448, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_18': {u'devType': 1, u'serialNumber': u'121630050381', u'lastReportDate': 1480302469, u'maxReportWatts': 270, u'lastReportWatts': 269}, 'No_19': {u'devType': 1, u'serialNumber': u'121630046741', u'lastReportDate': 1480302474, u'maxReportWatts': 270, u'lastReportWatts': 225}}`

Which is back to dict - and flattendict works well.

Not sure see a simple way - not to say there isn't one though!

Glenn

**Review by DaveL17 — APPROVED** [review]

**Review by DaveL17 — COMMENTED** [review]
Commit.

**Pull request merged**
